### ISSUE TITLE
sorry for useless issue

### ISSUE THREAD

**Issue by Vorshim92** [dark-vex/infra-cd#246]
Ciao Davide! Mi chiamo Stefano (Vorshim92). Ti ho letto sul puntotecnico sul thread del Fastgate. Per caso ci possiamo sentire un attimo su telegram? (se ce l'hai sempre). Ti lascio il mio utente https://t.me/Vorshim92 
Mi servirebbe giusto qualche consiglio per capire come sbloccarlo. Non ci sto riuscendo purtroppo. Non capisco come mai, ho visto che a te diceva il DHCP Discover della VLAN835. Io ho la stessa versione identica tua, anche di firmware, e non riesce a dargli l'ip, lo vede ma niente. 
Scusa lo spam issue in questa repo. Ovviamente cancellala subito dopo che hai letto. :)

**Comment by dark-vex** [comment]
Ciao, ti ho risposto al PM che mi hai mandato sul forum
